name: "Notify Teams"
on:
  push:
    branches: [docker_apache2]
  pull_request:
    branches: [docker_apache2]

jobs:

  send_team_update:         
    runs-on: ubuntu-latest
    steps:
      - name: Composite actions to send team update
        uses: dee-github/Test_Projects/action4@test_accurint
        with:
          repository_name: 'multi_factor_auth'
          repository_path: 'main'
          GH_PAT: ${{secrets.GH_PAT}}
