name: "Notify Teams"
on:
  push:
    branches: [docker_apache2]
  pull_request:
    branches: [docker_apache2]

jobs:

  send_team_update:         
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: dee-github/Test_Projects
          path: ./.github/test
          ref: test_accurint
          token: ${{inputs.GH_PAT}}
          fetch-depth: '0'
          
      - name: Composite actions to send team update
        uses: ./.github/test/action5
        with:
          repository_name: 'multi_factor_auth'
         
